services:
  ollama:
    image: ollama/ollama:latest
    container_name: inference_ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
